- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    project_name: "Test-project"
    ansible_user: "steffen"
    base_project_path: "/home/{{ ansible_user }}/ansible"
  tasks:

      - name: Create the Ansible project directory
        file:
          path: "{{ base_project_path }}/{{ project_name }}/{{ item }}"
          state: directory
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          mode: '0755'
        loop:
          - "staging"
          - "production"
          - "group_vars"
          - "host_vars"
          - "library"
          - "module_utils"
          - "filter_plugins"
          - "lookup_plugins"
          - "/roles/common/handlers"
          - "/roles/common/templates"
          - "/roles/common/files"
          - "/roles/common/vars"
          - "/roles/common/defaults"
          - "/roles/common/meta"
          - "/roles/common/tasks"
          - "/roles/common/library"
          - "/roles/common/module_utils"
          - "/roles/common/lookup_plugins"
      
      - name: Create the Ansible template files
        file:
          path: "{{ base_project_path }}/{{ project_name }}/{{ item }}"
          state: touch
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          mode: '0755'
          force: no
        loop:
          - "ansible.cfg"
          - "staging/inventory"
          - "production/inventory"
          - "site.yml"
          - "host_vars/hostname1.yml"
          - "host_vars/hostname2.yml"
          - "group_vars/group1.yml"
          - "group_vars/group2.yml"
          - "roles/common/tasks/main.yml"
          - "roles/common/handlers/main.yml"
          - "roles/common/templates/ntp.conf.j2"
          - "roles/common/files/file.txt"
          - "roles/common/vars/main.yml"
          - "roles/common/defaults/main.yml"
          - "roles/common/meta/main.yml"
